                                          class
                                          Removed
                                          {
                                          Removed
                                          (
                                          )
                                          {
                                          String
                                          s
                                          ;
                                          }
                                          }
